### ISSUE TITLE
Instagram Daily CheckList 

### ISSUE THREAD

**Issue by vignesh-reddy** [vignesh-reddy/GlaMate#1]
#### Morning 15 Minute Breakdown

- [x] 5 minutes - Engage with new followers
- [ ] 8 minutes - Engage with existing followers
- [ ] 2 minutes - Check previous days analytics and fill the analytics sheet

#### 10:30 AM
- [ ] Post or Reel

#### 2:00 PM 
- [ ] Enage with 10 similar pages
  - [ ] like atleast 25 posts
  - [ ] comment on atleast 5 
  - [ ] Repost a story

#### 7:00 PM
- [ ] 2nd Story

#### 9:00 PM
- [ ] 2nd Post(if any)
